apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: kubeconfiggenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      initContainers:
      - name: kubeconfiggenerator
        image: docker.io/nishantapatil3/kubeconfiggenerator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: kubeconfigvolume
            mountPath: /kubeconfigs
      volumes:
        - name: kubeconfigvolume
          emptyDir: {}
