apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: kubeconfigGenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - name: kubeconfigGenerator
        image: docker.io/nishantapatil3/kubeconfigGenerator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: kubeconfigVolume
            mountPath: /kubeconfig
      volumes:
        - name: kubeconfigVolume
          emptyDir: {}
